name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  REGISTRY: ghcr.io
  API_IMAGE_NAME: real-talk-api
  WEB_IMAGE_NAME: real-talk-web

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Test packages
        run: |
          pnpm install
          pnpm test

      - name: Create .env file for API
        run: echo "${{ secrets.ENV_FILE }}" > packages/api/.env

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: packages/api
          push: ${{ github.event_name == 'push' }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.API_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create .env file for web
        run: echo "${{ secrets.ENV_FILE }}" > packages/web/.env

      - name: Build and push web image
        uses: docker/build-push-action@v5
        with:
          context: packages/web
          push: ${{ github.event_name == 'push' }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.WEB_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
